#!/bin/sh
php -q /zeus/controller/console.php site_jobs
php -q /zeus/controller/console.php site_jobs
php -q /zeus/controller/console.php site_jobs
php -q /zeus/controller/console.php site_jobs
php -q /zeus/controller/console.php site_jobs
php -q /zeus/controller/console.php site_jobs
php -q /zeus/controller/console.php site_jobs
php -q /zeus/controller/console.php site_jobs
php -q /zeus/controller/console.php site_jobs
php -q /zeus/controller/console.php site_jobs
php -q /zeus/controller/console.php site_jobs
php -q /zeus/controller/console.php site_jobs
php -q /zeus/controller/console.php site_jobs
php -q /zeus/controller/console.php site_jobs
php -q /zeus/controller/console.php site_jobs
php -q /zeus/controller/console.php site_jobs
php -q /zeus/controller/console.php site_jobs
php -q /zeus/controller/console.php site_jobs
php -q /zeus/controller/console.php site_jobs
php -q /zeus/controller/console.php site_jobs
php -q /zeus/controller/console.php site_jobs
php -q /zeus/controller/console.php site_jobs
php -q /zeus/controller/console.php site_jobs
php -q /zeus/controller/console.php site_jobs
php -q /zeus/controller/console.php site_jobs
php -q /zeus/controller/console.php site_jobs
php -q /zeus/controller/console.php site_jobs
php -q /zeus/controller/console.php site_jobs
php -q /zeus/controller/console.php site_jobs
php -q /zeus/controller/console.php site_jobs
php -q /zeus/controller/console.php site_jobs
php -q /zeus/controller/console.php site_jobs
php -q /zeus/controller/console.php site_jobs
php -q /zeus/controller/console.php site_jobs
php -q /zeus/controller/console.php site_jobs
php -q /zeus/controller/console.php site_jobs
php -q /zeus/controller/console.php site_jobs
php -q /zeus/controller/console.php site_jobs
php -q /zeus/controller/console.php site_jobs
php -q /zeus/controller/console.php site_jobs
php -q /zeus/controller/console.php site_jobs
php -q /zeus/controller/console.php site_jobs
php -q /zeus/controller/console.php site_jobs
php -q /zeus/controller/console.php site_jobs
php -q /zeus/controller/console.php site_jobs
php -q /zeus/controller/console.php site_jobs
php -q /zeus/controller/console.php site_jobs
php -q /zeus/controller/console.php site_jobs
php -q /zeus/controller/console.php site_jobs
php -q /zeus/controller/console.php site_jobs
php -q /zeus/controller/console.php site_jobs
php -q /zeus/controller/console.php site_jobs
php -q /zeus/controller/console.php site_jobs
php -q /zeus/controller/console.php site_jobs
php -q /zeus/controller/console.php site_jobs
php -q /zeus/controller/console.php site_jobs
php -q /zeus/controller/console.php site_jobs
php -q /zeus/controller/console.php site_jobs
php -q /zeus/controller/console.php site_jobs
php -q /zeus/controller/console.php site_jobs