#!/bin/sh
php -q /zeus/controller/console.php update_miner_stats
php -q /zeus/controller/console.php update_miner_stats
php -q /zeus/controller/console.php update_miner_stats
php -q /zeus/controller/console.php update_miner_stats
php -q /zeus/controller/console.php update_miner_stats
php -q /zeus/controller/console.php update_miner_stats
php -q /zeus/controller/console.php update_miner_stats
php -q /zeus/controller/console.php update_miner_stats
php -q /zeus/controller/console.php update_miner_stats
php -q /zeus/controller/console.php update_miner_stats
php -q /zeus/controller/console.php update_miner_stats
php -q /zeus/controller/console.php update_miner_stats
php -q /zeus/controller/console.php update_miner_stats
php -q /zeus/controller/console.php update_miner_stats
php -q /zeus/controller/console.php update_miner_stats
php -q /zeus/controller/console.php update_miner_stats
php -q /zeus/controller/console.php update_miner_stats
php -q /zeus/controller/console.php update_miner_stats
php -q /zeus/controller/console.php update_miner_stats
php -q /zeus/controller/console.php update_miner_stats
